#!/usr/bin/env python3
"""E2 case generator: tickets at five levels between two sibling intents.

For each pair in data/design.json, asks the generator model for tickets that
are clearly A, lean A, are even, lean B, are clearly B, given only the two
intents' descriptions (from data/boundary.onto). Writes every prompt and raw
response to data/generation/, and the cases to data/cases.jobs and
data/labels.json. Needs OPENROUTER_API_KEY. Standard library only.
"""
import json, os, re, urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
design = json.loads((HERE / "data/design.json").read_text())
src = (HERE / "data/boundary.onto").read_text()
about = {m.group(1): m.group(2) for m in re.finditer(r'^\s+([a-z_]+): Ticket -> \w+ "([^"]+)"', src, re.M)}

LEVELS = list(design["levels"])
PROMPT = """You write realistic customer-support tickets for testing a ticket router.

Two intents the router must tell apart:
A = {a}: {about_a}
B = {b}: {about_b}

Write {n} tickets for each level below ({total} tickets in all), each 1-3 sentences, in a customer's own voice, varied in tone and detail. Never name the intents or use their exact wording.
- clear_a: plainly A, not B.
- lean_a: mostly A, with some features of B.
- even: genuinely ambiguous between A and B; a careful person could not tell which.
- lean_b: mostly B, with some features of A.
- clear_b: plainly B, not A.

Answer with JSON only: {{"tickets": [{{"level": "clear_a", "text": "..."}}, ...]}}"""


def ask(prompt):
    body = json.dumps({
        "model": design["generator"]["model"],
        "messages": [{"role": "user", "content": prompt}],
        "response_format": {"type": "json_object"},
    }).encode()
    req = urllib.request.Request(design["generator"]["endpoint"], data=body, headers={
        "Authorization": "Bearer " + os.environ["OPENROUTER_API_KEY"],
        "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=180) as r:
        return json.loads(r.read())


jobs, labels = [], {}
for p in design["pairs"]:
    n = design["per_level"]
    prompt = PROMPT.format(a=p["a"], b=p["b"], about_a=about[p["a"]], about_b=about[p["b"]],
                           n=n, total=n * len(LEVELS))
    raw = ask(prompt)
    (HERE / f"data/generation/{p['id']}.json").write_text(json.dumps({"prompt": prompt, "response": raw}, indent=1))
    content = raw["choices"][0]["message"]["content"]
    tickets = json.loads(content[content.index("{"):content.rindex("}") + 1])["tickets"]
    count = {lv: 0 for lv in LEVELS}
    for t in tickets:
        lv = t["level"]
        if lv not in count or count[lv] >= n:
            continue
        count[lv] += 1
        cid = f"E2-{p['id']}-{lv}-{count[lv]}"
        target = design["levels"][lv]
        labels[cid] = {"pair": p["id"], "kind": p["kind"], "level": lv,
                       "intent": p[target] if target else None, "a": p["a"], "b": p["b"]}
        jobs.append("Ticket: " + json.dumps({"id": cid, "goal": t["text"], "ticket": t["text"]}))
    missing = {lv: n - c for lv, c in count.items() if c < n}
    print(p["id"], "ok" if not missing else f"missing {missing}")

(HERE / "data/cases.jobs").write_text(
    "# E2 cases, generated by generate.py (see data/generation/ for prompts and raw answers).\n"
    + "\n".join(jobs) + "\n")
(HERE / "data/labels.json").write_text(json.dumps(labels, indent=1) + "\n")
print(len(jobs), "cases")
